### ISSUE TITLE
接口数据好像出问题了

### ISSUE THREAD

**Issue by Winton1988** [LiangWuCode/2019-nCov-api#1]
/ncov/statistics/totalDataOne这个接口的chinaDayAddList这个字段原本有新增的治愈率的，今天好像无法获取了。是数据有调整了吗？

**Comment by Winton1988** [comment]
dailyNewAddHistory，chinaDayList，dailyHealRateHistory，这几个字段也没数据了

**Comment by LiangWuCode** [comment]
已处理。
