### ISSUE TITLE
怎么有的接口不能用了

### ISSUE THREAD

**Issue by Stone-s** [LiangWuCode/2019-nCov-api#4]
大佬，我用你提供的接口写了一个APP，准备参加一个比赛，我今天发现腾讯的疫情百科接口不能用了，是腾讯的原因吧，还有就是你这个接口能支撑多长时间，近几个月应该能用吧

**Comment by Stone-s** [comment]
是预防指南的不能用了，检查诊断还有数据

**Comment by LiangWuCode** [comment]
哪个接口？   短时间内应该还是可以的。       接口的源码也是开源的    可以自行运行，本地跑也是可以的。

**Comment by LiangWuCode** [comment]
数据是可以获取到的，我通过腾讯的地址直接访问，也是需要很长时间的，多尝试一下就好了，关于接口提供时间，短期内应该是支持的。    如果不再提供在线的可以自行将代码clone下来，本地运行即可。

**Comment by Stone-s** [comment]
> 数据是可以获取到的，我通过腾讯的地址直接访问，也是需要很短的，多尝试一下就好了，关于接口提供时间，短期内应该是支持的。如果不再提供在线的可以自行将代码clone下来，本地运行即可。
感谢
